/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { EventAppAbi, EventAppAbiInterface } from "../EventAppAbi";
const _abi = [
  {
    type: "function",
    name: "test_function",
    inputs: [],
    outputs: [
      {
        type: "bool",
        name: "",
      },
    ],
  },
];

export class EventAppAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EventAppAbiInterface {
    return new Interface(_abi) as unknown as EventAppAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): EventAppAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as EventAppAbi;
  }
}
