/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventAppAbi } from "./EventAppAbi";

export { EventAppAbi__factory } from "./factories/EventAppAbi__factory";
